name: Upload File to Repo

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Filename to upload"
        required: true
      content:
        description: "Base64 encoded file content"
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Save Uploaded File
        run: |
          echo "${{ github.event.inputs.content }}" | base64 --decode > uploads/${{ github.event.inputs.filename }}

      - name: Commit and Push Changes
        run: |
          git config --global user.email "projectdr.birgunj@gmail.com"
          git config --global user.name "projectdr-birgunj"
          git add uploads/
          git commit -m "Uploaded ${{ github.event.inputs.filename }} via GitHub Actions"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/projectdr-birgunj/Muktinath-photos.git main
