name: Upload Files to GitHub  # Name of the workflow

on:
  push:  # Runs the workflow whenever you push changes
    branches:
      - main  # Change this if using a different branch
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  upload:
    runs-on: ubuntu-latest  # Runs the job on GitHub's Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Clones the repo so we can modify it

      - name: Configure Git
        run: |
          git config --global user.email "projectdr.birgunj@gmail.com"
          git config --global user.name "projectdr-birgunj"

      - name: Upload File to Repo
        run: |
          echo "Your file content" > uploads/example.txt  # Create a test file
          git add uploads/example.txt
          git commit -m "Upload example.txt via GitHub Actions"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/projectdr-birgunj/Muktinath-photos.git main
